### PR TITLE
Create unique RabbitMQ virtual host for each test method.

### PR DESCRIPTION
**Pull request by proofit404**

### CODE REVIEW

**Comment by proofit404** [comment]
Hi,

In this PR you can see the way you need to use RabbitMQ in your tests. I'm not familiar with uwsgi, looks like it do some file descriptors related magic. So you can see fd related traceback in the output. My knowledge is limited in this area, so I can't help in further debugging.

**Comment by proofit404** [comment]
Maybe this is it https://travis-ci.org/tovmeod/uwsgi-asgi/jobs/195615410#L213

**Comment by tovmeod** [comment]
enabling threads doesn't seem to help: https://travis-ci.org/tovmeod/uwsgi-asgi/jobs/196340961#L207

please see the branch pr1 https://github.com/tovmeod/uwsgi-asgi/tree/pr1

**Comment by proofit404** [comment]
I don't know much about uwsgi, since I use gunicorn in all projects before. I'll try to research preparation steps uwsgi does to run worker with layer instance. Maybe we just initialize environment the wrong way.

**Comment by tovmeod** [comment]
it seems new_channel() is not returning, so the test is timing out and killing the threads.

[edit]
not really, sometimes it doesn't even reach this code, I suspect the problem is the thread, probably blocking the process, is using threads essential, could it be optional?

**Pull request closed without merging**
